#!/usr/bin/env bash
#install nginx 
apt-get update -y
apt-get install -y nginx
ufw allow 'Nginx HTTP'
chown -R "$USER":"$USER" /var/www/
echo "Holberton School" > /var/www/html/index.nginx-debian.html
service nginx restart
