#!/usr/bin/env bash
#install nginx 
apt-get update -y
apt-get install -y nginx
ufw allow 'Nginx HTTP'
chown -R "$USER":"$USER" /var/www/
echo "Holberton School" > /var/www/html/index.nginx-debian.html
echo "Ceci n'est pas une page" > /var/www/html/error404.html
sed -i '/server_name _/a error_page 404 /error404.html;\nlocation = /error404.html\n{\nroot /var/www/html/;\ninternal;\n}' /etc/nginx/sites-available/default
service nginx restart
