#!/usr/bin/env bash
# Configure HAproxy
apt-get update
apt-get install haproxy=1.6.\*
echo -e "backend web-backend\n\tbalance roundrobin\n\tserver web1 104.196.68.125:80 check\n\tserver web2 34.75.60.0:80 check\n" >> /etc/haproxy/haproxy.cfg
echo -e "frontend http\n\tbind *:80\n\tmode http\n\tdefault_backend web-backend\n" >> /etc/haproxy/haproxy.cfg
service haproxy restart