#!/usr/bin/env bash
# this script displays "Holberton School" 10 times
COUNT=0
while [ $COUNT -lt 10 ]
do
	echo "Holberton School"
	if [ $COUNT -eq 8 ]
	then
		echo "Hi"
		     fi
			let COUNT=COUNT+1
done