#!/usr/bin/env bash
# displays the time for 12 hours and 59 minutes:
# display hours from 0 to 12
# display minutes from 1 to 59
HOUR=0
MIN=1
while [ $HOUR -lt 13 ]
do
	let MIN=1
	echo "Hour: $HOUR"
	while [ $MIN -lt 60 ]
	do
		echo "$MIN"
		          let MIN=MIN+1
			           done
					     let HOUR=HOUR+1
done