#!/usr/bin/env bash
# fix nginx port 8080
pkill apache2
chmod 644 /etc/nginx/nginx.conf
sed -i 's/80 default_server/8080 default_server' /etc/nginx/sites-available/default
sudo -u nginx service nginx restart 
