#!/usr/bin/env bash
# Bash script must be 7 lines long or less using what you did for task #1
pkill apache2
chmod 644 /etc/nginx/nginx.conf
sed -i 's/80 default_server/8080 default_server/' /etc/nginx/sites-available/default
sudo -u nginx service nginx restart